config/routes.rb
Rails.application.routes.draw do
    root to: "teams#index"
    resources :teams do
      resources :games
    end
    resources :games
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :away_team, class_name: "Team", foreign_key: :away_team_id
  belongs_to :home_team, class_name: "Team", foreign_key: :home_team_id

  before_save :generate_season
  before_save :generate_winner
  before_save :generate_score_difference
  before_save :generate_betting_line_winner
  before_save :generate_over_under_success

  def generate_season
    if self.date.month < 2
      self.season = self.date.year - 1
    else
      self.season = self.date.year
    end
  end

  def generate_winner
    if self.home_team_score > self.away_team_score
      self.winner = self.home_team_id
    else
      self.winner = self.away_team_id
    end
  end

  def generate_score_difference
    self.score_difference = self.home_team_score - self.away_team_score
  end

  def generate_betting_line_winner
      if (self.home_team_score - self.away_team_score) > self.betting_line
        self.betting_line_winner = self.home_team_id
      else
        self.betting_line_winner = self.away_team_id
      end
  end

  def generate_over_under_success
    if (self.home_team_score + self.away_team_score) > self.over_under
      self.over_under_success = 1
    else
      self.over_under_success = 0
    end
  end

  def games
    return self.where("home_team_id = ? OR away_team_id = ?", self.id, self.id)
  end

  def home_team_wins
     self.winner == self.home_team_id
  end

  def away_team_wins
    self.winner == self.away_team_id
  end

  def self.betting_line_sum(games)
    games.map{|game| game.betting_line}.sum
  end

  def betting_line_success_count_home
    self.betting_line_winner == self.home_team_id
  end

  def betting_line_success_count_away
    self.betting_line_winner == self.away_team_id
  end

  def over_under_sum
    self.map{|game| game.over_under}.sum
  end

  def over_under_success_count
    self.over_under_success == 1
  end

  def all_years
    all_years = self.map{|game| game.season}.uniq.sort
  end

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :away_games, dependent: :destroy, class_name: "Game", foreign_key: :away_team_id
  has_many :home_games, dependent: :destroy, class_name: "Game", foreign_key: :home_team_id

  # accepts_nested_attributes_for :home_games, :away_games

  def games
    return Game.where("home_team_id = ? OR away_team_id = ?", self.id, self.id)
  end

  def game_count(games)
    games.count.to_f
  end

  def wins(games)
    games.where(winner: self.id).count
  end

  # def home_games
  #   Game.where("home_team_id = ?", self.id)
  # end

  def betting_line_sum(games)
    games.map{|game| game.betting_line}.sum
  end

  def betting_line_success_count(games)
    games.where(betting_line_winner: self.id).count
  end

  def over_under_sum(games)
    games.map{|game| game.over_under}.sum
  end

  def over_under_success_count(games)
    games.map{|game| game.over_under_success}.sum
  end

  def self.all_divisions
    all_divisions = self.all.map{|team| team.division}.uniq.sort
  end

  def self.all_conferences
    all_conferences = self.all.map{|team| team.conference}.uniq.sort
  end

  def self.find_all_with_division(division)
    if division
      division == "All" ? self.all : self.where(division: division)
    else
      []
    end
  end

  def self.find_all_with_conference(conference)
    if conference
      conference == "All" ? self.all : self.where(conference: conference)
    else
      []
    end
  end

  def self.all_years(team)
    all_years = team.games.map{|game| game.season}.uniq.sort
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index

    #record the params to grab from the browser
    @season = params[:season]

    # get all teams based on domain query
    if @season
      @games = Game.where(season: @season)
    else
      @games = Game.all
      @season = 'All'
    end

    # get all the available years
    @seasons = @games.map{|game| game.season}.uniq.sort

    #various statistics
    @game_count = @games.count

    @home_team_win_percent = ((@games.select{|game| game.home_team_wins}.count.to_f / @game_count.to_f) * 100).to_f.round(1)
    @away_team_win_percent = ((@games.select{|game| game.away_team_wins}.count.to_f / @game_count.to_f) * 100).to_f.round(1)

    @betting_lines = (@games.map(&:betting_line).sum / @game_count).round(1)
    # @betting_lines = (Game.betting_line_sum(@games) / @game_count).round(1)

    @over_unders = (@games.map(&:over_under).sum / @game_count).round(1)

    @betting_line_success_rate_home = ((@games.select{|game| game.betting_line_success_count_home}.count.to_f / @game_count.to_f) * 100).round(1)

    @betting_line_success_rate_away = ((@games.select(&:betting_line_success_count_away).count.to_f / @game_count.to_f) * 100).round(1)

    @over_success_rate = ((@games.map(&:over_under_success).sum.to_f / @game_count.to_f) * 100).round(1)
    
    @under_success_rate = 100 - @over_success_rate

  end

  def new
    # @team = Team.find(params[:team_id])
    @game = Game.new
    @teams = Team.all
  end

  def create
    @game = Game.new(game_params)
    @game.save!
    redirect_to games_path
  end

  def show
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    @game.update(game_params)

    redirect_to team_path(@game)
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path
  end

  private
  def game_params
    params.require(:game).permit(:date, :away_team, :home_team, :away_team_score, :home_team_score, :betting_line, :over_under, :away_team_id, :home_team_id, :season, :manual_creation)
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    # remember the domain name selected
    @division = params[:division]
    @conference = params[:conference]

    # get all teams based on domain query
    if @division
      @teams = Team.find_all_with_division(@division)
    elsif @conference
      @teams = Team.find_all_with_conference(@conference)
    else
      @teams = Team.all
      @division = 'All'
      @conference = 'All'
    end

    # get all the available divisions and conferences
    @divisions = @teams.all_divisions
    @conferences = @teams.all_conferences

  end

  def show
    # remember the domain name selected
    @team = Team.find(params[:id])

    #record the params to grab from the browser
    @season = params[:season]
    @location = params[:location]

    # get all the available years
    @seasons = Team.all_years(@team)
    @locations = ['Home', 'Away']

    # get all teams based on domain query
    if @season
      @games = @team.games.where(season: @season)
    elsif @location
      if @location = 'Home'
        @games = @team.games.where(home_team: @team.id)
      elsif @location = 'Away'
        @games = @team.games.where(away_team: @team.id)
      end
    else
      @games = @team.games
      @season = 'All'
      @location = 'All'
    end

    #various statistics
    @game_count = @team.game_count(@games)

    @wins = @team.wins(@games)

    @losses = @game_count.to_i - @wins

    @betting_lines = (@team.betting_line_sum(@games) / @game_count).round(1)

    @over_unders = (@team.over_under_sum(@games) / @game_count).round(1)

    @win_percent = ((@wins.to_f/@game_count) * 100).round(1)

    @betting_line_success_rate = ((@team.betting_line_success_count(@games) / @game_count) * 100).round(1)

    @over_under_success_rate = ((@team.over_under_success_count(@games) / @game_count) * 100).round(1)

  end

  private
  def team_params
    params.require(:team).permit(:name, :division, :conference)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<div class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand"> <%= link_to 'BestBet', root_path, class: "name" %></div>
    </div>

  </div>
</div>

<div class="team_name">Games</div>

<div class="log_new_game"><%= link_to "Log new game", new_game_path %></div>

  <div class='col-md-1'>
    <h3>Filter</h3>
    <h4>Season</h4>
    <div class='btn-group-vertical'>
      <a href='<%= games_path %>'
        type='button'
        class='btn btn-default
        <%= 'btn-primary btn-active' if @season == 'All' %>
        btn-sm'
      >All</a>
        <% @seasons.each do |year| %>
          <a href='/games?season=<%= year %>'
            type='button'
            class='btn btn-default
            <%= 'btn-primary btn-active' if @season == year %>
            btn-sm'
          ><%= year %></a>
        <% end %>
    </div>
  </div>

  <div class='col-md-2'>
    <table class='table table-striped table-bordered .table-sm'>
      <tbody>
        <tr>
          <td class="data_title">Total Games Played</td>
          <td class="data_row"><%= @game_count %></td>
        </tr>
        <tr>
          <td class="data_title">Home Win Percentage</td>
          <td class="data_row"><%= @home_team_win_percent %>%</td>
        </tr>
        <tr>
          <td class="data_title">Away Win Percentage</td>
          <td class="data_row"><%= @away_team_win_percent %>%</td>
        </tr>
        <tr>
          <td class="data_title">Average Betting Line</td>
          <td class="data_row"><%= @betting_lines %></td>
        </tr>
        <tr>
          <td class="data_title">Win Percentage when Betting the Line on Home Team</td>
          <td class="data_row"><%= @betting_line_success_rate_home %>%</td>
        </tr>
        <tr>
          <td class="data_title">Win Percentage when Betting the Line on Away Team</td>
          <td class="data_row"><%= @betting_line_success_rate_away %>%</td>
        </tr>
        <tr>
          <td class="data_title">Average Over/Under</td>
          <td class="data_row"><%= @over_unders %></td>
        </tr>
        <tr>
          <td class="data_title">Win Percentage on Betting the Over</td>
          <td class="data_row"><%= @over_success_rate %>%</td>
        </tr>
        <tr>
          <td class="data_title">Win Percentage on Betting the Under</td>
          <td class="data_row"><%= @under_success_rate %>%</td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class='col-md-6 games'>
    <table class='table table-striped'>
      <thead>
        <tr>
          <th>Date</th>
          <th>Away Team</th>
          <th>Home Team</th>
          <th>Score</th>
          <th>Betting Line</th>
          <th>Over Under</th>
          <th></th>
        </tr>
      </thead>
      <% @games.each do |game| %>
        <tr>
          <td><%= game.date %></td>
          <td><%= game.away_team.name %></td>
          <td><%= game.home_team.name %></td>
          <td><%= game.away_team_score%> - <%= game.home_team_score%></td>
          <td><%= game.betting_line %></td>
          <td><%= game.over_under %></td>
          <td>
            <% if game.manual_creation %>
              <%=link_to "Delete Game", game_path(game), method: :delete %>
            <% end %>
          </td>

        </tr>
      <% end %>
    </table>
  </div>

app/views/games/new.html.erb
<div class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand"> <%= link_to 'BestBet', root_path, class: "name" %></div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li><%= link_to "Go to Games", games_path, class: "games_path" %></li>
      </ul>
    </div>
  </div>
</div>


<div class="team_name">Log a New Result</div>

<%= form_for @game do |f| %>
  <%= f.date_field(:date) %>
  <br>
  <br>
  <%= f.label :away_team%>
  <%= f.select(:away_team_id, options_for_select(@teams.map{|team| [team.name, team.id]})) %>
  <br>
  <br>
  <%= f.label :home_team%>
  <%= f.select(:home_team_id, options_for_select(@teams.map{|team| [team.name, team.id]})) %>
  <br>
  <br>
  <%= f.label :away_team_score%>
  <%= f.text_field :away_team_score %>
  <br>
  <br>
  <%= f.label :home_team_score %>
  <%= f.text_field :home_team_score %>
  <br>
  <br>
  <%= f.label :betting_line %>
  <%= f.text_field :betting_line%>
  <br>
  <br>
  <%= f.label :over_under %>
  <%= f.text_field :over_under %>
  <br>
  <br>
  <%= f.hidden_field :manual_creation, value: true %>
  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bestbet</title>
  <%= stylesheet_link_tag 'https://getbootstrap.com/dist/css/bootstrap.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Holtwood+One+SC' %>
  <%= javascript_include_tag 'https://getbootstrap.com/dist/js/bootstrap.js' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
<%= yield %>
</div>


</body>
</html>